{{- if .Values.pgadmin.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.pgadmin.fullnameOverride }}
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.pgadmin.fullnameOverride }}
  template:
    metadata:
      labels:
        app: {{ .Values.pgadmin.fullnameOverride }}
    spec:
      containers:
      - name: pgadmin
        image: {{ .Values.pgadmin.image.repository }}:{{ .Values.pgadmin.image.tag }}
        imagePullPolicy: {{ .Values.pgadmin.image.pullPolicy }}
        ports:
        - containerPort: 80
          name: http
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: {{ .Values.pgadmin.env.email | quote }}
        - name: PGADMIN_DEFAULT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.pgadmin.fullnameOverride }}-secret
              key: password
        - name: PGADMIN_CONFIG_SERVER_MODE
          value: "False"
        resources:
          {{- toYaml .Values.pgadmin.resources | nindent 10 }}
        volumeMounts:
        - name: pgadmin-data
          mountPath: /var/lib/pgadmin
      volumes:
      {{- if .Values.pgadmin.persistence.enabled }}
      - name: pgadmin-data
        persistentVolumeClaim:
          claimName: {{ .Values.pgadmin.fullnameOverride }}-pvc
      {{- else }}
      - name: pgadmin-data
        emptyDir: {}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.pgadmin.fullnameOverride }}
  namespace: {{ .Values.namespace.name }}
spec:
  type: {{ .Values.pgadmin.service.type }}
  ports:
  - port: {{ .Values.pgadmin.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: {{ .Values.pgadmin.fullnameOverride }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.pgadmin.fullnameOverride }}-secret
  namespace: {{ .Values.namespace.name }}
type: Opaque
stringData:
  password: {{ .Values.pgadmin.env.password | quote }}
---
{{- if .Values.pgadmin.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pgadmin.fullnameOverride }}-pvc
  namespace: {{ .Values.namespace.name }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.pgadmin.persistence.storageClass }}
  storageClassName: {{ .Values.pgadmin.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.pgadmin.persistence.size }}
{{- end }}
{{- end }}
