{{- if .Values.postgresql-storage.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.postgresql-storage.fullnameOverride }}
  namespace: {{ .Values.namespace.name }}
spec:
  serviceName: {{ .Values.postgresql-storage.fullnameOverride }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.postgresql-storage.fullnameOverride }}
  template:
    metadata:
      labels:
        app: {{ .Values.postgresql-storage.fullnameOverride }}
    spec:
      containers:
      - name: postgresql
        image: postgres:15-alpine
        ports:
        - containerPort: {{ .Values.postgresql-storage.service.port }}
          name: postgresql
        env:
        - name: POSTGRES_USER
          value: {{ .Values.postgresql-storage.auth.username | quote }}
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.postgresql-storage.fullnameOverride }}-secret
              key: password
        - name: POSTGRES_DB
          value: {{ .Values.postgresql-storage.auth.database | quote }}
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        resources:
          {{- toYaml .Values.postgresql-storage.primary.resources | nindent 10 }}
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
  {{- if .Values.postgresql-storage.primary.persistence.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      {{- if .Values.postgresql-storage.primary.persistence.storageClass }}
      storageClassName: {{ .Values.postgresql-storage.primary.persistence.storageClass | quote }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.postgresql-storage.primary.persistence.size }}
  {{- else }}
      volumes:
      - name: data
        emptyDir: {}
  {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgresql-storage.fullnameOverride }}
  namespace: {{ .Values.namespace.name }}
spec:
  type: {{ .Values.postgresql-storage.service.type }}
  ports:
  - port: {{ .Values.postgresql-storage.service.port }}
    targetPort: postgresql
    protocol: TCP
    name: postgresql
  selector:
    app: {{ .Values.postgresql-storage.fullnameOverride }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgresql-storage.fullnameOverride }}-secret
  namespace: {{ .Values.namespace.name }}
type: Opaque
stringData:
  password: {{ .Values.postgresql-storage.auth.password | quote }}
  postgres-password: {{ .Values.postgresql-storage.auth.postgresPassword | quote }}
{{- end }}
