{{- if .Values.redis.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.redis.fullnameOverride }}
  namespace: {{ .Values.namespace.name }}
spec:
  serviceName: {{ .Values.redis.fullnameOverride }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.redis.fullnameOverride }}
  template:
    metadata:
      labels:
        app: {{ .Values.redis.fullnameOverride }}
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: {{ .Values.redis.service.port }}
          name: redis
        {{- if .Values.redis.auth.enabled }}
        command:
        - redis-server
        - --requirepass
        - $(REDIS_PASSWORD)
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.redis.fullnameOverride }}-secret
              key: password
        {{- end }}
        resources:
          {{- toYaml .Values.redis.master.resources | nindent 10 }}
        volumeMounts:
        - name: data
          mountPath: /data
  {{- if .Values.redis.master.persistence.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      {{- if .Values.redis.master.persistence.storageClass }}
      storageClassName: {{ .Values.redis.master.persistence.storageClass | quote }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.redis.master.persistence.size }}
  {{- else }}
      volumes:
      - name: data
        emptyDir: {}
  {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redis.fullnameOverride }}
  namespace: {{ .Values.namespace.name }}
spec:
  type: {{ .Values.redis.service.type }}
  ports:
  - port: {{ .Values.redis.service.port }}
    targetPort: redis
    protocol: TCP
    name: redis
  selector:
    app: {{ .Values.redis.fullnameOverride }}
---
{{- if .Values.redis.auth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.redis.fullnameOverride }}-secret
  namespace: {{ .Values.namespace.name }}
type: Opaque
stringData:
  password: {{ .Values.redis.auth.password | quote }}
{{- end }}
{{- end }}
