{{- if .Values.security.enabled }}
{{- if .Values.security.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.security.namespace.name }}
{{- end }}
{{- end }}
---
{{- if .Values.server.enabled }}
{{- if .Values.server.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.server.namespace.name }}
{{- end }}
{{- end }}
---
{{- if .Values.storage.enabled }}
{{- if .Values.storage.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.storage.namespace.name }}
{{- end }}
{{- end }}
---
{{- if .Values.ui.enabled }}
{{- if .Values.ui.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.ui.namespace.name }}
{{- end }}
{{- end }}
